### ISSUE TITLE
Create tracker class template

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#12]
**Tasks**
- [x] Creates a tracker.py file consisting of a single class Tracker
- [x] Create initializer that takes in a filename for a video on the server
- [x] Create a get_background function
- [x] Create a detect_targets function
- [x] Create a process_frame function
- [x] Create a process_video function

**Accepted Criteria**
Given: A developer has imported Tracker
When: A developer instantiates a tracker and calls each of its functions
Then: No errors occur

**Done Done**
Does not implement any of the functions, should just create them
All code passes style guide
All commits pushed and merged into master
