### ISSUE TITLE
Create route in Flask to handle endpoint

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#13]
**Tasks**
- [ ] In views.py, add a route named /generateData
- [ ] It should take a mp4 file as a parameter
- [ ] It should return the resulting csv file name if success. Return null if failure.

**Accepted Criteria**
Given: A developer needs to generate csv data from an mp4 file
When: A developer calls the endpoint with proper parameters
Then: No errors occur and a proper data file returns

**Done Done**
Endpoint works as desired
All code passes style guide
All commits pushed and merged into master
