### ISSUE TITLE
Create javascript class to handle parsing the csv data

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#27]
**Tasks**
- [x] Create Parser.js file under client
- [x] Create a model class to represent tracklets in javascript
- [x] get() method to access specific frame data
- [x] next(), previous() methods to access next and previous frames
- [x] next5(), previous5() methods to access frames corresponding with "jump-forward" and "jump-backward" buttons
- [x] Optional: Look into using papa parse module
- [x] Should return a bounding box, not specific data. E.g. x, y, width, height, theta

**Acceptance Criteria**
- Should be able to get data for a specific frame

**Done Done**
- All code passes style guides
- All commits pushed and merged into master
