### ISSUE TITLE
Create base styles

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#31]
**Tasks**
- [ ] Create styles for all headers
- [ ] Create styles for text
- [ ] Create style for background of page

**Acceptance Criteria**
- Stuff looks dope

**Done Done**
- All code conforms to style guide
- All commits pushed and merged into master
