### ISSUE TITLE
Create bounding box class in javascript

### ISSUE THREAD

**Issue by amatlock22** [hlane6/biotracker#32]
**Tasks**
- [x] Create boundingBox.js file
- [x] Create a constructor method that builds bounding box based on parameters

**Parameters**
- [x] x, column of image
- [x] y, row of image
- [x] width, width of bounding box
- [x] height, height of bounding box
- [x] theta, direction bounding box faces

**Acceptance Criteria**
- Bounding box instance is returned correctly based on given parameters

**Done Done**
- All code passes style guides
- All commits pushed and merged into master
