### ISSUE TITLE
As a user, I would like to see the corrections I have made so far

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#39]
**Tasks**
- [ ] Update tracker component to hold corrections in its state
- [ ] Create component to render the corrections

**Acceptance Criteria**
- [ ] A user can select a box and assign it a new id
- [ ] A user's correction propagates throughout the video
