### ISSUE TITLE
Document existing python methods and classes

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#59]
**Tasks**
- [ ] Add proper py docs to every public method throughout every module and class in the application
- [ ] Add type hints throughout every module in the application
- [ ] Update all methods and instance variables to be private or public as documented in the detailed design

**Acceptance Criteria**
- All public methods are pydoced
- All private instance variable and private methods use the _ convention
- All methods add type hinting as described in PEP 484

**Done Done**
- All code conforms to style guide
- All commits pushed and merged into master
