### ISSUE TITLE
Create a base Jinja template for other templates to inherit from

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#6]
**Tasks**
- [ ] Create .html template under app/templates which includes a {% block content %} to allow inheriting
- [ ] Create a .css file which includes the style for the base under app/static/css
- [ ] Update index.html to inherit from this template

**Acceptance Criteria**
Given: A user is on homepage
Then: A user sees at least a header and footer with no content inbetween

**Done Done Criteria**
Code adheres to style guides
All commits pushed
