### ISSUE TITLE
As a user I want to have a UI where I can edit the data.

### ISSUE THREAD

**Issue by austinHerring** [hlane6/biotracker#62]
**Tasks**
- [ ] Add an interface to add a box
- [ ] Add an interface to re remove a box
- [ ] Add an interface to switch box IDs

**Acceptance Criteria**
- The style is easy to use and intuitive

**Done Done**
- All code conforms to style guide
- All commits pushed and merged into master
