### ISSUE TITLE
Research bundling application

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#64]
**Tasks**
- [ ] Include python library as file inside a zipped so that when it is unzipped, it can be referenced without installing it (opencv, munkres, numpy, scipy, flask)
- [ ] Include react library and its dependencies as part of the tar
- [ ] Creating an install script that can be run after unzipping the application
