### ISSUE TITLE
Create scripts to run individual components of the application

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#65]
**Tasks**
- [ ] A tracker script which generates a tracklets.csv from a video file using the tracker.py (input of video)
- [ ] An association script which associates tracks given a tracklets.csv file and produces a tracks.csv (input of tracklets.csv)
- [ ] A generate video script which takes in a video file and tracks.csv to generate a new video with bounding boxes in it (input of video and tracks.csv)
- [ ] A script to start the server locally
