### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by hlane6** [hlane6/biotracker#69]
**Tasks**
- [ ] Remove carden-biotracker, demo, react-biotracker, and videoframe-test folders from root directory
- [ ] Move all of app's contents into root directory
- [ ] Remove all of flask reference files
- [ ] Create scripts folder to hold all python files
- [ ] Move app/biotracker/models folder into scripts folder
- [ ] Rename app/electron to client
- [ ] Remove old app/client folder
- [ ] Remove biotracker.egg-info
